name: Perform Release

on:
  push:
    tags:
      - "*/v[0-9]+.[0-9]+.[0-9]+*"

jobs:
  release-perform:
    if: ${{ github.repository_owner == 'dazuma' }}
    env:
      ruby_version: "2.7"
    runs-on: ubuntu-latest
    steps:
      - name: Install Ruby ${{ env.ruby_version }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ env.ruby_version }}
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Checkout gh-pages
        uses: actions/checkout@v2
        with:
          ref: "gh-pages"
          path: "tmp"
      - name: Install Toys
        run: "gem install --no-document toys"
      - name: Perform release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          toys release _perform --verbose \
            "--api-key=${{ secrets.RUBYGEMS_API_KEY }}" \
            "--user-name=${{ secrets.GIT_USER_NAME }}" \
            "--user-email=${{ secrets.GIT_USER_EMAIL }}" \
            "--enable-releases=${{ secrets.ENABLE_RELEASES }}" \
            < /dev/null
